name: ci

on:
  push:

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Verificar IP de Tailscale
        run: |
          echo "Mostrando IP de Tailscale..."
          tailscale ip

      - name: Instalar sshpass
        run: |
          echo "Instalando sshpass para autenticación con contraseña..."
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Probar conexión SSH usando contraseña
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PASS: ${{ secrets.PASSWORD }}
        run: |
          echo "Intentando conexión SSH con $SSH_USER@$SSH_HOST..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 'echo "Conexión SSH exitosa"'

      - name: Crear archivo en el servidor
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PASS: ${{ secrets.PASSWORD }}
        run: |
          echo "Creando archivo hello.txt en el servidor..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 'echo "Hello World" > hello.txt'
          echo "Archivo creado exitosamente en el servidor."
