name: ci

on:
  push:
    branches:
      - main

jobs:
  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jnoriadev/portfolio:latest

  update-lxc:
    runs-on: ubuntu-latest
    needs: dockerhub-publish
    steps:
      - name: Set up tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Update LXC
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PASS: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" '
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
          '
